name = "grom"
version = "0.0.0"
description = "Gleam wrapper for the Discord API"
licenses = ["Apache-2.0", "MIT"]
repository = { type = "custom", url = "https://tangled.sh/@folospior.me/grom"}

[dependencies]
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.1.0 and < 2.0.0"
multipart_form = ">= 1.1.0 and < 2.0.0"
operating_system = ">= 1.0.1 and < 2.0.0"
repeatedly = ">= 2.1.2 and < 3.0.0"
stratus = { git = "git@github.com:folospior/stratus", ref = "new_on_close" }
status_code = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
